name: Stage - Development

on:
  issues:
    types: [labeled]

jobs:
  development:
    if: >
      github.event.issue.state == 'open' &&
      (contains(github.event.issue.labels.*.name, 'needs:develop') ||
       contains(github.event.issue.labels.*.name, 'needs:develop-revision'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      actions: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup stage context
        id: setup
        uses: actions/github-script@v7
        with:
          script: |
            const { data: issue } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            
            // Get all comments for comprehensive context
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              per_page: 30
            });

            // Filter out deleted/empty comments
            const validComments = comments.data.filter(comment => 
              comment.body && 
              comment.body.trim() !== '' && 
              !comment.body.includes('[DELETED]')
            );

            // Check if this is initial development or revision
            const labels = issue.labels.map(label => label.name);
            const isRevision = labels.includes('needs:develop-revision');
            
            // Find the last human who mentioned the bot
            const lastHumanComment = validComments
              .reverse()
              .find(comment => 
                comment.user.type === 'User' && 
                comment.body.includes('@claude-dev-truefrontier')
              );
            
            const lastHumanUser = lastHumanComment ? lastHumanComment.user.login : null;
            core.setOutput('is_revision', isRevision.toString());
            core.setOutput('issue_details', JSON.stringify({
              ISSUE_NUMBER: context.issue.number,
              ASSIGNEES: issue.assignees || [],
              STATE: issue.state,
              CREATED_AT: issue.created_at,
              UPDATED_AT: issue.updated_at,
            }));
            core.setOutput('issue_description', issue.body || '');
            core.setOutput('recent_comments', JSON.stringify(validComments));
            core.setOutput('last_human_user', lastHumanUser);

      - name: Run Development Implementation
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          branch_prefix: "feature/issue-${{ github.event.issue.number }}-"
          use_sticky_comment: true
          allowed_bots: 'claude[bot]'
          claude_args: |
            --allowedTools "Bash,Edit,MultiEdit,Write,Glob,Grep,Read,Task,TodoWrite,WebFetch,WebSearch,mcp__github__get_issue_comments,mcp__github__add_issue_comment,mcp__github__create_branch,mcp__github__create_pull_request"
          prompt: |
            You are acting as a Senior Software Engineer implementing features based on specifications, technical plan, and task breakdown.

            <context>
              <issue_details>${{ steps.setup.outputs.issue_details }}</issue_details>
              <issue_description>${{ steps.setup.outputs.issue_description }}</issue_description>
              <recent_comments>${{ steps.setup.outputs.recent_comments }}</recent_comments>
              <is_revision>${{ steps.setup.outputs.is_revision }}</is_revision>
              <last_human_user>${{ steps.setup.outputs.last_human_user }}</last_human_user>
            </context>

            ## Your Task
            ${{ steps.setup.outputs.is_revision == 'true' && '
            This is a REVISION based on previous feedback. Review the recent comments for bug reports, test failures, or requested changes and address them.
            ' || '
            This is INITIAL DEVELOPMENT. Implement the complete feature based on approved specifications, technical plan, and task breakdown from previous comments.
            ' }}

            ## CRITICAL: Always Post Comment
            You MUST post a comment with your development summary, test results, and implementation details. This is not optional - every workflow run must produce a visible comment for the user to review. Your development progress and results will automatically be posted as a comment to the issue.

            ## Implementation Process

            ### 1. Review Previous Work (CRITICAL - Required Context)
            - Use `mcp__github__get_issue_comments` to retrieve all issue comments and review the complete conversation history
            - **MUST review the 3 required previous stage comments:**
              1. **Specification Stage Comment** - What needs to be built and why (user stories, requirements, acceptance criteria)
              2. **Technical Plan Stage Comment** - How it will be built (architecture, technology choices, implementation strategy)
              3. **Task Breakdown Stage Comment** - Step-by-step implementation tasks (T001, T002, etc. with dependencies)
            - **EQUALLY IMPORTANT: Review all human feedback comments** - Human responses to each stage are critical for understanding:
              - What was approved/rejected in specifications
              - Technical plan modifications or concerns raised
              - Task breakdown adjustments or prioritization changes
              - Any additional requirements or constraints added by humans
            - **Integration Analysis:** Understand how human feedback shaped each stage's evolution

            ### 2. Execute Task Breakdown (Follow Approved Plan)
            - **Follow the exact task sequence** from the approved task breakdown comment (T001 → T002 → T003...)
            - **Respect human modifications** - If humans requested changes to the task order or priorities, follow their guidance
            - **Implement systematically:** Setup → Tests → Implementation → Integration → Validation
            - **Check dependencies:** Ensure prerequisite tasks are complete before starting dependent tasks
            - **Reference specific files and components** identified in the task breakdown
            - **Follow parallel task guidance** - Work on [P] marked tasks simultaneously when possible

            ### 3. Development Cycle
            1. **Implement Tasks**: Follow the prioritized task list step-by-step
            2. **Test as You Go**: Run tests after each significant change
            3. **Verify Integration**: Ensure changes work with existing code
            4. **Run Full Test Suite**: Execute all tests to verify nothing is broken
            5. **Refactor**: Improve code quality while keeping tests passing
            6. **Document**: Update documentation as needed

            ### 4. Integration and Final Testing
            - Run complete test suite using the project's test commands
            - Fix any integration issues that arise
            - Ensure no existing functionality is broken
            - Verify all new functionality works end-to-end
            - Test edge cases and error conditions

            ## Testing Requirements (Critical)
            - **ALL tests must pass** before considering implementation complete
            - Run the project's existing test suite to ensure compatibility
            - Create appropriate tests based on the project's testing framework:
              - Unit tests for business logic
              - Integration tests for external dependencies
              - End-to-end tests for user workflows
            - **Iterate until 100% of tests pass** - do not accept failing tests

            ## Code Quality Standards
            - Follow the project's existing coding standards and conventions
            - Maintain consistency with existing codebase patterns
            - Implement proper error handling and validation
            - Add appropriate comments and documentation
            - No placeholder code or TODOs in final implementation

            ## Git Workflow
            - Create feature branch: `feature/issue-${{ github.event.issue.number }}-[description]`
            - Make atomic commits with clear messages
            - Follow conventional commit format when possible

            ## Required Actions (Execute in Order)
            
            **1. FIRST: Always Post Your Development Summary Comment Above**
            - You MUST explicitly call `mcp__github_comment__create_comment` or `mcp__github_comment__update_claude_comment` to post a comprehensive development summary
            - **Include Context Summary** - Briefly reference which specifications, technical plan elements, and task breakdown items you implemented
            - **Include Human Feedback Integration** - Note how you incorporated human feedback from previous stage reviews
            - Include a "What I'm Doing" section that explains your implementation approach
            - Post a comprehensive development summary including:
              - What was implemented (features, files changed, tests created)
              - All test results (must show 100% passing tests)
              - Branch name and commit details
              - Any issues encountered and how they were resolved
              - Final implementation status and readiness for PR
              - **MUST INCLUDE: "Create a PR" link** using the format: `[Create a PR](https://github.com/${{ github.repository }}/compare/main...BRANCH_NAME)`
            - This happens automatically when you include the summary in your response
            - Do not proceed to step 2 until the comment is posted
            
            **2. THEN: Update Workflow State**
            Only after successfully posting your development summary comment, execute these commands:

            ```bash
            # Remove the current stage label
            gh issue edit ${{ github.event.issue.number }} \
              --remove-label "needs:develop" \
              --remove-label "needs:develop-revision"

            # Set to review state and assign to human
            gh issue edit ${{ github.event.issue.number }} \
              --add-label "review:develop" \
              --add-assignee "${{ steps.setup.outputs.last_human_user }}"
            ```

            ## Success Criteria
            - All specified requirements are implemented and working
            - All project tests pass using the project's test suite
            - Code follows the project's best practices and conventions
            - No breaking changes to existing functionality
            - Feature branch is ready for PR creation
            - Implementation is complete with no placeholder code
            - All tasks from the task breakdown are completed

            **Remember: This is the final implementation stage. Everything must be production-ready and fully tested before completion.**